# Copy paste (and modify) from VST SDK, as JUCE did not play nice ...

function(mod_smtg_set_exported_symbols target exported_symbols_file)
    if(MSVC)
        set_target_properties(${target} PROPERTIES LINK_FLAGS "/DEF:\"${exported_symbols_file}\"")
    elseif(XCODE)
        set_target_properties(${target} PROPERTIES XCODE_ATTRIBUTE_EXPORTED_SYMBOLS_FILE "${exported_symbols_file}")
    else()
        set_target_properties(${target} PROPERTIES LINK_FLAGS "-exported_symbols_list \"${exported_symbols_file}\"")
    endif()
endfunction()

function(mod_smtg_add_vst3plugin target sdkroot)
    set(sources ${ARGN})
    add_library(${target} MODULE ${sources})
    if(MAC)
        set_target_properties(${target} PROPERTIES BUNDLE TRUE)
        if(XCODE)
            set_target_properties(${target} PROPERTIES XCODE_ATTRIBUTE_GENERATE_PKGINFO_FILE "YES")
            set_target_properties(${target} PROPERTIES XCODE_ATTRIBUTE_WRAPPER_EXTENSION "vst3")
        else()
            set_target_properties(${target} PROPERTIES BUNDLE_EXTENSION "vst3")
        endif()
        mod_smtg_set_exported_symbols(${target} "${sdkroot}/public.sdk/source/main/macexport.exp")
    elseif(WIN)
        set_target_properties(${target} PROPERTIES SUFFIX ".vst3")
        set_target_properties(${target} PROPERTIES LINK_FLAGS "/EXPORT:GetPluginFactory")
    elseif(LINUX)
        EXECUTE_PROCESS( COMMAND uname -m COMMAND tr -d '\n' OUTPUT_VARIABLE ARCHITECTURE )
        set(target_lib_dir ${ARCHITECTURE}-linux)
        set_target_properties(${target} PROPERTIES PREFIX "")
    endif()
endfunction()
