name: JUCE artifacts (ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pkgconf libalsa-ocaml-dev libfreetype-dev libgl-dev libcurl-ocaml-dev libwebkit2gtk-4.0-dev libgtk-3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with: 
        name: ubuntu-artifacts
        path: |
          ${{github.workspace}}/build/JUCE/PhasePhdgr_artefacts/Release
          ${{github.workspace}}/build/JUCE/PhasePhdgrFx_artefacts/Release
        retention-days: 2
