name: JUCE artifacts (macos)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2.0'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --build-config ${{env.BUILD_TYPE}} --output-on-failure

    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v4
      with: 
        name: windows-artifacts
        path: |
          ${{github.workspace}}/build/JUCE/PhasePhdgr_artefacts/Release
          ${{github.workspace}}/build/JUCE/PhasePhdgrFx_artefacts/Release
        retention-days: 2
